---
- name: Proxmox setup
  hosts: localhost
  gather_facts: true
  roles:
    - storage
    - repos
    - serhii9132.base_layer.common
    - serhii9132.base_layer.utilities
    - ssh
    - serhii9132.base_layer.git
    - accounts
    - nag_screen
  