---
- name: Apply sshd.conf from template
  ansible.builtin.template:
    src: sshd.conf.j2
    dest: "{{ __ssh_config_path }}/{{ __ssh_config_name }}"
    owner: root
    group: root
    mode: '644'
  notify: Restart ssh service
